workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Create Flutter project
        script: |
          flutter create --project-name daftar --org com.daftar .
          cp -r /clone/lib/* lib/
          cp /clone/pubspec.yaml pubspec.yaml
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-shrink
    artifacts:
      - build/**/outputs/**/*.apk
