workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          flutter create --project-name daftar --org com.daftar tmp_project
          cp -r lib tmp_project/
          cp pubspec.yaml tmp_project/
          cd tmp_project
          flutter pub get
          flutter build apk --release --no-shrink
    artifacts:
      - tmp_project/build/**/outputs/**/*.apk
